default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: ideaz_dev
  username: postgres
  password: <%= ENV['IDEAZ_DATABASE_PASSWORD_DEV'] %>

test:
  <<: *default
  host: localhost
  database: ideaz_test
  username: postgres
  password: <%= ENV['IDEAZ_DATABASE_PASSWORD_TEST'] %>

production:
  <<: *default
  database: ideaz_production
  username: ideaz
  password: <%= ENV['IDEAZ_DATABASE_PASSWORD'] %>
